### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by itdevatgadgetstory** [itdevatgadgetstory/ggsrepair-frontend#17]

**Comment by atip0ra** [comment]
**File path** : .github/workflows/docker-image.yml

**Secrete** : Add secrete in GitHub secrete
- DOCKERHUB_USERNAME
- DOCKERHUB_TOKEN

```
name: ci

on:
  push:
    branches:
      - 'test'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: atip0ra/testrepo:v1.0.0
```
